application: stateprices
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: main.app

libraries:
- name: django
  version: "latest"

env_variables:
  DJANGO_SETTINGS_MODULE: 'stateprices.settings'
  SP_IDEALISTA_API_KEY: 'XAcJJUvzdZuO0btqPFUHgSGtAAb80pmc'
  SP_DEFAULT_ADDRESS: '43.5417747,-5.6648064'
  SP_DEFAULT_DISTANCE: '500'
  SP_DEFAULT_OPERATION: 'rent'